language: java
 
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "L8UhU685MtYW8j4NgWszlXxYURlSLLZtLQwvNHEuGhdevonEGnhpJglcdaFyEQCWzipaBtc+MpIUs+MIUaw/I9a2IhSZfMB5iXywG0z1iLQdEpOrBQi35uhahKJ51ne61lB+TkDEfCUlaNNZRmC83+G1thDaKDCDkSnzYhlWJ6rOKiTIcapjghr5dsjt0sG7PgMYEsVeCMx0DlZQAxO1rObjdPYB2eJ5XUrcMOJVmEJb6zv7o28C0xlzV4ZV/FqM7K1hQhhwuTbZICLcTqpGIgMl7iQe5LYflb1JrcP5k2rvdN6nQEplzLno0n0mF38BEZTt/pQRTlM1KGxWhggGVNbv+EwgeM/V/VNaNw7swIcAJpIMvTvr4jtSnTeqM7mRIIqIVgADkHVJapWV3lTVFaQkCJ80JyXk/RWXCt3F7DXG01gY9u4OfgHuoBUa9PfA00bosrKoF5FO8zFEWo9Ri9DATAcf7cOysq2u650gTBIe88HEAYHumZMODkAO6+gtRe1sm4AFJP1CQW2+v3kFLo+8sMBDlciRhEfS+ivxjae4B1WcC0CNg32MNpy0Xq/wnUsBTQrgvXnxvPrK4bGOK3b3BRsZwq6F5E8A2f8J5ZdgKZNz92vOQblNnhMNuWYIkChxIoYd4YFVwFyL59otzLod+YrhhGLAVRO6uyoq7uQ=" 

after_success:
  - python .travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com
